### ISSUE TITLE
cannot read property 'encrypt' for undefined

### ISSUE THREAD

**Issue by ImadBahsoun** [Mastercard/client-encryption-nodejs#11]
i got that error when i try to call the encrypt method .. that's the code:
const fle = new require('mastercard-client-encryption').FieldLevelEncryption(config);
let encryptedRequestPayload = fle.encrypt(endpoint, header, body);

what should fle return ?? it returns undefined always ?

**Comment by ech0s7r** [comment]
Hi @ImadBahsoun,

You should first import the `mastercard-client-encryption` [module](https://nodejs.org/api/modules.html), then create an instance of `FieldLevelEncryption` invoking the constructor, for instance:

```js
const clientEncryption = require('mastercard-client-encryption');
const fle = new clientEncryption.FieldLevelEncryption(config);

let encrypted = fle.encrypt(endpoint, header, body);
```
In one line (*note the brackets*):
```js
const fle = new (require('mastercard-client-encryption')).FieldLevelEncryption(config);

let encrypted = fle.encrypt(endpoint, header, body);
```

Please, check out the updated documentation [here](https://github.com/Mastercard/client-encryption-nodejs#performing-field-level-encryption-and-decryption) or a working [example](https://github.com/Mastercard/mastercard-api-client-tutorial/blob/master/nodejs/test/api/TokenizeApi.spec.js#L204) that use the `FieldLevelEncryption` interceptor.
