### ISSUE TITLE
can you plz merge dependabot's  node-forge 0.10.0 pull request?

### ISSUE THREAD

**Issue by yuriabaev** [Mastercard/client-encryption-nodejs#19]
im having dependecy vulnerbility 
can you plz merge dependabot's node-forge 0.10.0 pull request?
https://github.com/Mastercard/client-encryption-nodejs/pull/18

**Comment by jaaufauvre** [comment]
Hi @yuriabaev,
Thanks for the reminder!
We created a new GitHub release: https://github.com/Mastercard/client-encryption-nodejs/releases
We will let you know when the package is published to npmjs.org: https://www.npmjs.com/package/mastercard-client-encryption
Best regards,

**Comment by jaaufauvre** [comment]
`client-encryption-nodejs` v1.1.0 is available: https://www.npmjs.com/package/mastercard-client-encryption
I'm closing this issue.
