### ISSUE TITLE
Facing CRYPTOGRAPHY_ERROR while calling API

### ISSUE THREAD

**Issue by voraparth91** [Mastercard/client-encryption-nodejs#21]
Hi,

I am trying to run the mocha test available in the repo (createTokenize API). However with that, I am using the sandbox credentials (consumerKey, oAuth privateKey) from the developer portal. I was unable to find the certificate (mastercard) for field level encryption  in the portal. So I am using the one in this repo -> test/res/test_certificate.cert

However on hitting the API call, I am getting following response:

```
{
  "errorCode": "CRYPTOGRAPHY_ERROR",
  "errorDescription": "Cryptography Error",
  "errors": [
    {
      "source": "INPUT",
      "reasonCode": "CRYPTOGRAPHY_ERROR",
      "description": "Cryptography Error"
    }
  ],
  "responseId": "123456",
  "supportsAuthentication": false
}
```

Any pointers on what could be wrong I am doing here?

**Comment by ech0s7r** [comment]
Hi @voraparth91, 

The certificate `test/res/test_certificate.cert` included in this repo was created for testing purposes (library unit test, etc...) and it is not an accepted certificate for consuming Mastercard APIs in Sandbox. 
The sandbox certificates to use are available in the API documentation on https://developer.mastercard.com/. If you are unable to find it, please reach out to the support team as per the options listed here: https://developer.mastercard.com/support/. They can help you finding the sandbox certificate for the specific service you are trying to consume.
