### ISSUE TITLE
Test and update the MDES Digital Enablement configuration

### ISSUE THREAD

**Issue by jaaufauvre** [Mastercard/client-encryption-nodejs#5]
`cardInfo` is now `fundingAccountInfo`

**Comment by ech0s7r** [comment]
@jaaufauvre, This is exactly the reason why they should be auto-generated.

**Comment by ech0s7r** [comment]
Added here: https://github.com/Mastercard/client-encryption-nodejs/wiki/Mastercard-Services-Configuration#mdes-digital-enablement-api.
